PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:<http://www.w3.org/2002/07/owl#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
PREFIX et: <http://www.semanticweb.org/imiko/ontologies/2017/11/ENVO_trial#>

SELECT * 
FROM <http://enviropackets.org/epo>
WHERE { 
?thing rdf:type ?desc .
?desc a owl:Restriction ;
owl:onProperty et:denotes ;
owl:allValuesFrom ?stuff .
}

